"""Initialise base db structure

Revision ID: a125a4e7f751
Revises: 
Create Date: 2024-02-22 12:13:41.931996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a125a4e7f751'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productfootprint',
    sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(), nullable=True, comment='The product footprint identifier.'),
    sa.Column('precedingPfIds', sa.JSON(), nullable=True, comment='non-empty set of preceding product footprint identifiers without duplicates.'),
    sa.Column('specVersion', sa.String(), nullable=True, comment='The version of the ProductFootprint data specification.'),
    sa.Column('version', sa.Integer(), nullable=True, comment='The version of the ProductFootprint.'),
    sa.Column('created', sa.String(), nullable=True, comment='The timestamp of the creation of the ProductFootprint.'),
    sa.Column('updated', sa.String(), nullable=True, comment='The timestamp of the ProductFootprint update.'),
    sa.Column('status', sa.Enum('ACTIVE', 'DEPRECATED', name='productfootprintstatus'), nullable=True, comment='The status of the product footprint.'),
    sa.Column('statusComment', sa.String(), nullable=True, comment='If defined, the value should be a message explaining the reason for the current status.'),
    sa.Column('validityPeriodStart', sa.String(), nullable=True, comment='If defined, the start of the validity period of the ProductFootprint.'),
    sa.Column('validityPeriodEnd', sa.String(), nullable=True, comment='The end (excluding) of the valid period of the ProductFootprint.'),
    sa.Column('companyName', sa.String(), nullable=True, comment='The name of the company that is the ProductFootprint Data Owner.'),
    sa.Column('companyIds', sa.JSON(), nullable=True, comment='The set of Uniform Resource Names (URN) identifying the ProductFootprint Data Owner.'),
    sa.Column('productDescription', sa.String(), nullable=True, comment='The free-form description of the product.'),
    sa.Column('productIds', sa.JSON(), nullable=True, comment='The set of ProductIds that uniquely identify the product.'),
    sa.Column('productCategoryCpc', sa.String(), nullable=True, comment='A UN Product Classification Code (CPC) that the given product belongs to.'),
    sa.Column('productNameCompany', sa.String(), nullable=True, comment='The trade name of the product.'),
    sa.Column('comment', sa.String(), nullable=True, comment='Additional information related to the product footprint.'),
    sa.Column('pcf', sa.JSON(), nullable=True, comment='The carbon footprint of the given product.'),
    sa.Column('extensions', sa.JSON(), nullable=True, comment='If defined, 1 or more data model extensions associated with the ProductFootprint.'),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_productfootprint_id'), 'productfootprint', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_productfootprint_id'), table_name='productfootprint')
    op.drop_table('productfootprint')
    # ### end Alembic commands ###
